### ISSUE TITLE
Installation failing while installing tests

### ISSUE THREAD

**Issue by sigsevneo** [manojgudi/sciscipy-1.0.0#1]
Before setting up Sandhi, it is recommended to setup sciscipy-1.0.0. While installation, I am however facing an issue with the Test module not installing. Could you help me out please?

```
Appending .bashrc to source /etc/environment file... 
  Testing... 
running test
['tests.test_matrix', 'tests.test_call', 'tests.test_read']
Traceback (most recent call last):
  File "./setup.py", line 122, in <module>
    cmdclass = { 'test': TestCommand}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 86, in run
    tests = TestLoader().loadTestsFromNames(testfiles)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_matrix'
```

**Comment by manojgudi** [comment]
Hello Anagh,

I'll require information on the environment you have,
1. Which OS are you using
2.  Which scilab version are you using

**Comment by sigsevneo** [comment]
Hi Manoj,
1. I am using Ubuntu 14.04.2 LTS, which is the recommended version.
2. I was installing this as it is required for Sandhi. I have not installed Scilab separately. Please tell me how to do that. Is that the problem which is causing this error?

**Comment by manojgudi** [comment]
On Nov 6, 2015 11:23 AM, "Anagh Singh" notifications@github.com wrote:

> Hi Manoj,
> 
> I am using Ubuntu 14.04.2 LTS, which is the recommended version.
> I was installing this as it is required for Sandhi. I have not installed
> Scilab separately. Please tell me how to do that. Is that the problem which
> is causing this error?

Hi, this sciscipy is an additional library to use scilabs computational
engine from sandhi.. It is not an essential one.

Either ways, to install sciscipy wrapper you require scilab
You can install scilab like this:
sudo apt-get install scilab

Once that is done. You can try installing sciscipy again and it should
work.

Lemme know if it doesn't work..

**Comment by sigsevneo** [comment]
It still gives the same error even after installing scilab separately. It is failing the same point as earlier.

**Comment by manojgudi** [comment]
On Fri, Nov 6, 2015 at 1:47 PM, Anagh Singh notifications@github.com
wrote:

> It still gives the same error even after installing scilab separately. It
> is failing the same point as earlier.

This module was built and tested on Ubuntu 12.04 and works flawlessly on it.
However, gimme a day to reproduce this on a ubuntu 14.04 machine,
additionally I am CC'ing sandhi team to see if they have any idea about
this.

**Comment by manojgudi** [comment]
Only in few systems this error is coming. I am not able to reproduce this
error on my ubuntu 14.04 system

Ambikeshwar

**Comment by manojgudi** [comment]
Hello Anagh,

please build sciscipy from ubuntu14.04 branch of the same repo
https://github.com/manojgudi/sciscipy-1.0.0/tree/ubuntu14.04

I've fixed and tested it to work for ubuntu14.04 running scilab5.5

**Comment by sigsevneo** [comment]
Thanks Manoj. This version builds properly.
